[nfs]
172.31.45.122 ansible_ssh_user='ec2-user'

[webservers]
172.31.35.199 ansible_ssh_user='ec2-user'
172.31.42.162 ansible_ssh_user='ec2-user'

[db]
172.31.44.14 ansible_ssh_user='ec2-user' 

[lb]
172.31.37.73 ansible_ssh_user='ubuntu'