- hosts: all
  become: true
- name: Include dynamic variables
  import_playbook: ../static-assignments/common.yml
  include_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: webservers
- name: Webserver assignment
  ansible.builtin.import_playbook: ../static-assignments/webservers.yml